### PR TITLE
I updated tags 

### PR DESCRIPTION
**Pull request by jason-drouhard**

### CODE REVIEW

**Review by juansanchez-stratusgrid — CHANGES_REQUESTED** [review]
Tried to run the code on local repository but it does not run the terraform apply because the file tags.tf has a blank space in the name (made with spacebar--> 'tags.tf_') so terraform does not read the file and an error happens. Also is recommended to put a carriage return so is posix compliance

**Review by StratusChris — COMMENTED** [review]
Should there even be a default value? Will this run successfully with that default value, or should the default be removed to make it a required value?

**Comment by juansanchez-stratusgrid** [comment]
It does run successfully with that default value, what will happen is that "cloudwatch_logs_group_path" will ask for a name for that path to a cloudwatch logs group, what i think is that if there is a default value that is an empty string as i changed it in the last commit, it may happen that different roles creation logs may go to the same cloud watch logs group which will be the following:

""arn:aws:logs:*:*:log-group::log-stream:*"" 

I personally think that is not a good idea, so it will be better to make it a required value so we specify always the intended logs_group_path that we want, I have already test the code removing the default value and it does work so it is ok if i commit with the change: "remove cloudwatch_logs_group_path deafult value" ?

**Comment by StratusChris** [comment]
Yes @juansanchez-stratusgrid - I agree that making it required would be the right option. Go ahead and push the commit and we'll approve and publish.

**Pull request merged**
